### ISSUE TITLE
fix: devcontainer kubernetes installation failures in arm64

### ISSUE THREAD

**Issue by get6** [42atomys/stud42#614]
### Describe the bug

When installing the devcontainer an error as raised in arm64.

### To Reproduce

With command palette. execute this command: `Dev containers: Rebuild container` in arm64

### Expected behavior

It should install well and without errors.

### Relevant log output

```Shell
46.37 2024-06-18 07:02:51 URL:https://objects.githubusercontent.com/github-production-release-asset-2e65be/92702519/9708aa96-fd1f-4144-bde4-854420532167?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240618%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240618T070249Z&X-Amz-Expires=300&X-Amz-Signature=882eccb791822cd12be1ac16a2437d110659eda2d7df1ce9aeb1513b19c6b1d8&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=92702519&response-content-disposition=attachment%3B%20filename%3Dkubeseal-0.26.3-linux-arm64.tar.gz&response-content-type=application%2Foctet-stream [20070779/20070779] -> "kubeseal-0.26.3-linux-arm64.tar.gz" [1]
46.38 tar (child): kubeseal-0.26.3-linux-amd64.tar.gz: Cannot open: No such file or directory
[2024-06-18T07:02:52.060Z] 46.38 tar (child): Error is not recoverable: exiting now
46.38 tar: Child returned status 2
46.38 tar: Error is not recoverable: exiting now
------
[2024-06-18T07:02:52.062Z] failed to solve: process "/bin/sh -c ARCH=$([ \"`uname -m`\" = \"aarch64\" ] && echo \"arm64\" || echo \"amd64\") &&   apt-get update && export DEBIAN_FRONTEND=noninteractive   && apt-get -y install --no-install-recommends gnupg2 postgresql-client   iputils-ping dnsutils vim htop nano sudo curl build-essential zsh wget jq   fonts-powerline tig ca-certificates software-properties-common redis-tools &&   curl -LO \"https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${ARCH}/kubectl\" &&   install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&   kubectl version --client &&   curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash &&   wget --no-verbose --show-progress --progress=dot:mega -O /tmp/terraform.zip \"https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_${ARCH}.zip\" &&   unzip /tmp/terraform.zip -d /usr/local/bin/ &&   wget --no-verbose --show-progress --progress=dot:mega \"https://dl.min.io/client/mc/release/linux-$
[2024-06-18T07:02:52.062Z] {ARCH}/mc\" &&   install -m 755 mc /usr/local/bin/mc &&   KUBESEAL_VERSION=$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/tags | jq -r '.[0].name' | cut -c 2-) &&   if [ -z \"$KUBESEAL_VERSION\" ]; then   echo \"Failed to fetch the latest KUBESEAL_VERSION\";   exit 1;   fi &&   wget --no-verbose --show-progress --progress=dot:mega \"https://github.com/bitnami-labs/sealed-secrets/releases/download/v${KUBESEAL_VERSION}/kubeseal-${KUBESEAL_VERSION}-linux-${ARCH}.tar.gz\" &&   tar -xvzf kubeseal-${KUBESEAL_VERSION}-linux-amd64.tar.gz kubeseal &&   install -m 755 kubeseal /usr/local/bin/kubeseal" did not complete successfully: exit code: 2
[2024-06-18T07:02:52.066Z] Stop (46855 ms): Run: docker-compose --project-name stud42_devcontainer -f /Users/ittae/GitHub/stud42/.devcontainer/docker-compose.yaml -f /Users/ittae/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1718694125211.yml build
[2024-06-18T07:02:52.067Z] Error: Command failed: docker-compose --project-name stud42_devcontainer -f /Users/ittae/GitHub/stud42/.devcontainer/docker-compose.yaml -f /Users/ittae/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1718694125211.yml build
[2024-06-18T07:02:52.067Z]     at Km (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:429:525)
[2024-06-18T07:02:52.068Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-18T07:02:52.068Z]     at async QtA (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:429:2476)
[2024-06-18T07:02:52.068Z]     at async utA (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:409:3506)
[2024-06-18T07:02:52.068Z]     at async KtA (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:481:3865)
[2024-06-18T07:02:52.068Z]     at async eB (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[2024-06-18T07:02:52.068Z]     at async hrA (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:661:13373)
[2024-06-18T07:02:52.068Z]     at async lrA (/Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js:661:13114)
[2024-06-18T07:02:52.070Z] Stop (47396 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/ittae/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2a26cce4-7dce-474f-a380-80dc6199683a1718694123972 --workspace-folder /Users/ittae/GitHub/stud42 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/ittae/GitHub/stud42 --id-label devcontainer.config_file=/Users/ittae/GitHub/stud42/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/ittae/GitHub/stud42/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-06-18T07:02:52.070Z] Exit code 1
[2024-06-18T07:02:52.072Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ittae/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/ittae/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2a26cce4-7dce-474f-a380-80dc6199683a1718694123972 --workspace-folder /Users/ittae/GitHub/stud42 --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/ittae/GitHub/stud42 --id-label devcontainer.config_file=/Users/ittae/GitHub/stud42/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/ittae/GitHub/stud42/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-06-18T07:02:52.072Z] Exit code 1
```

### Version of software

v0.33

### Environment

Sandbox (https://sandbox.s42.dev)

### Additional context

Discord report : https://discord.com/channels/248936708379246593/1214996222566465648

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42atomys** [comment]
Hi, thanks for your contribution, I dont have a mac arm anymore and I cant test the new installation on it, I will try to test it with an arm codespace if you need help
